// VITE_API_BASE_URL is normally set in .env.local, auto-generated by
// vite.config.ts from backend/config.env for dev serving -- a production
// build (npm run build) instead writes it as an explicit empty string, so
// API_BASE becomes "" (relative/same-origin) rather than falling through to
// the literal fallback below (?? only triggers on null/undefined, not "").
// Same-origin is what lets the mobile client work from whatever host/IP a
// phone used to load the page, with no CORS handling needed.
export const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:10765";
export const WS_BASE = API_BASE.replace(/^http/, "ws");

const MOBILE_TOKEN_STORAGE_KEY = "owon-mobile-token";

// Set once by the mobile app after a successful PIN check (Mobile
// Requirements.txt item 2.2); stays null for the PC dashboard bundle, which
// never calls setMobileToken -- so apiFetch/wsUrl below are no-ops for it,
// identical to today's behavior.
let mobileToken: string | null = (() => {
  try {
    return localStorage.getItem(MOBILE_TOKEN_STORAGE_KEY);
  } catch {
    return null;
  }
})();

export function setMobileToken(token: string | null): void {
  mobileToken = token;
  try {
    if (token) localStorage.setItem(MOBILE_TOKEN_STORAGE_KEY, token);
    else localStorage.removeItem(MOBILE_TOKEN_STORAGE_KEY);
  } catch {
    // localStorage unavailable (private browsing etc.) -- the in-memory
    // value above still works for the rest of this page load.
  }
}

export function getMobileToken(): string | null {
  return mobileToken;
}

// A relative API_BASE ("") means WS_BASE is also "" -- and a scheme-less
// relative WebSocket URL is NOT safe to assume works: per the WebSocket
// constructor spec, a relative URL resolves against the page's origin but
// keeps the page's http/https scheme, which isn't ws/wss, so the constructor
// throws a SyntaxError. Build an explicit ws(s):// URL from location in that
// case; in dev mode (API_BASE absolute), WS_BASE is already a real ws://
// URL from the regex replace above, so just use it as before.
export function wsUrl(path: string): string {
  const base = API_BASE
    ? WS_BASE
    : `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host}`;
  const token = mobileToken ? `?token=${encodeURIComponent(mobileToken)}` : "";
  return `${base}${path}${token}`;
}

export class ApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

export async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, {
    headers: {
      "Content-Type": "application/json",
      ...(mobileToken ? { "X-Mobile-Token": mobileToken } : {}),
    },
    ...options,
  });

  if (!response.ok) {
    let detail = response.statusText;
    try {
      const body = await response.json();
      detail = body.detail ?? detail;
    } catch {
      // response body wasn't JSON; fall back to statusText
    }
    throw new ApiError(response.status, detail);
  }

  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}
